on:
  pull_request:
    branches:
      - main

jobs:
  checker:
    runs-on: ubuntu-latest
    name: PR Checker
    permissions: write-all
    steps:
      - name: Setup Python Environment
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - name: Run Checker
        run: |
          pip3 install pyyaml IPy
          OUTPUT=$(python3 script/checker.py ${{ steps.changed-files.outputs.all_changed_files }})
          echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV
      - name: Reply to PR
        uses: actions/github-script@v3
        if: always()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ env.MESSAGE }}
            })
